on:
  push:
    branches:
      - main
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout Code
      - name: Checkout Code
        uses: actions/checkout@v4

      # Step 2: Set Up Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: npm

      # Step 3: Install Dependencies
      - name: Install Dependencies
        run: npm ci

      # Step 4: Build the Project
      - name: Build the Project
        run: npm run build

      # Step 5: Debugging Environment
      - name: Debug Build Output
        run: |
          echo "Node version: $(node --version)"
          echo "NPM version: $(npm --version)"
          echo "Build directory contents:"
          ls -l build
          echo "Current working directory:"
          pwd

      # Step 6: Run Test Server Creation Script
      - name: Test Creation from Template
        run: |
          node ./build/index.js test-server --name test-server --description "Here is a test server"

      # Step 7: Validate Generated Project
      - name: Validate Generated Project
        run: |
          if [ -d "test-server" ]; then
            cd test-server
            npm install
            npm run build
            npm link
          else
            echo "test-server directory does not exist"
            exit 1
          fi
